# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
zero_array = np.zeros(10, dtype='int32')
print(zero_array)

[0 0 0 0 0 0 0 0 0 0]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
myarray = np.array([1,2,3])
memory_size = myarray.nbytes
print(memory_size)

24


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
array5 = np.zeros(10,dtype='int32')
array5[4]=1
print(array5)

[0 0 0 0 1 0 0 0 0 0]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
array6 = np.arange(start=10,stop=50)
print(array6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
array7 = np.sort(array6)[::-1]
print(array7)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
myarray = np.arange(start=0, stop=9)
array8 = myarray.reshape(3,3)
print(array8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
myarray = np.array([1,2,0,0,4,0])
array9 = myarray[myarray != 0]
print(array9)

[1 2 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [11]:
identity_matrix = np.identity(3)
print(identity_matrix)

identity_matrix_eye = np.eye(3)
print(identity_matrix_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [12]:
random_array = np.random.random((3,3,3))
print(random_array)

[[[0.63001498 0.43649956 0.20622529]
  [0.15384916 0.70280047 0.71013262]
  [0.11569672 0.18566489 0.15726882]]

 [[0.63224053 0.24918726 0.75086947]
  [0.7764673  0.70701159 0.91446703]
  [0.35635884 0.22722616 0.31358467]]

 [[0.41317658 0.71540583 0.00881105]
  [0.27018557 0.49603362 0.58625503]
  [0.55243958 0.385267   0.76247094]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [13]:
random_array1 = np.random.random((10,10))

print(np.min(random_array1))
print(np.max(random_array1))

0.00732726900461711
0.9693938945014466


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [14]:
random_array2 = np.random.random(30)
print(np.mean(random_array2))

0.5161323725536783


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
array = np.zeros((5,5))
array[0,:]=1
array[-1,:]=1
array[:,0]=1
array[:,-1]=1
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan
True
False
nan
False
True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [16]:
matrix = np.zeros((5,5))
diag_matrix = np.diag([0,1,2,3,4])
print(diag_matrix)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [17]:
matrix = np.zeros((8,8))
matrix[1::2, ::2] =1
matrix[::2, 1::2] =1

print(matrix)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [18]:
array = np.unravel_index(100,(6,7,8))
print(array)

(1, 5, 4)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [19]:
random_matrix = np.random.random((5,5))
ran_mean = np.mean(random_matrix)
ran_std = np.std(random_matrix)
norm_matrix = (random_matrix-ran_mean)/ran_std
print(norm_matrix)

[[-1.38925545  1.52072779 -0.2553546  -0.18710738  1.36003878]
 [-1.48294719  1.46786981  1.530524    0.52627981 -0.30988426]
 [-0.40649266 -0.80408262  0.12766432 -0.33068059 -0.95297754]
 [-1.33927764 -1.3560558  -0.83121001 -0.95477882  0.64096464]
 [ 1.58994962  0.95944569 -0.30184359  0.50967318  0.66881052]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [20]:
dtype = np.dtype([("R",np.ubyte),("G",np.ubyte),
                 ("B",np.ubyte),("A",np.ubyte)])
print(dtype)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [21]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
B = np.array([[1,2],[3,4],[5,6]])

array21 = np.dot(A,B)
print(array21)

[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [22]:
array = np.array([8,16,5,1,7,2,6,4,0])
array[(array>3) & (array<8)] *= -1
print(array)

[ 8 16 -5  1 -7  2 -6 -4  0]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [23]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Z< Z >Z

벡터Z를 자기 자신과 비교하고 결과를 다시 Z와 비교하는 것은 유효한 구문이 아니다.

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [24]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-24-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-24-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-24-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [28]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
common_values = np.intersect1d(Z1,Z2)
print(common_values)

[1 2 5 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [29]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-29-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

 : numpy.sqrt() 함수로는 음의 제곱근을 구할 수 없음. nan을 반환.

 넘파이에는 복소수를 다루기 위한 np.emath.sqrt()함수가 제공됨. 이를 이용해서 음수의 제곱근을 표현할 수 있음.

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [31]:
np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [36]:
A=np.array([8,12,4])
B=np.array([3,4,2])

add = np.add(A,B)
np.divide(A,2, out=A)
np.negative(A,out=A)
np.multiply(add, A,out=A)

print(A)

UFuncTypeError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [42]:
random_array = np.random.random(5)*10
print(random_array)

#방법1
method1 = random_array // 1
print(method1)

#방법2
method2 = random_array - (random_array%1)
print(method2)

[0.24134644 6.2863668  4.83839709 4.08771327 4.66416134]
[0. 6. 4. 4. 4.]
[0. 6. 4. 4. 4.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [48]:
row_values = np.arange(5)

A = np.zeros((5,5))
A += row_values
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [44]:
A = np.random.random(10)
A.sort()
print(A)

[0.15400493 0.17427277 0.21622165 0.28611752 0.47623528 0.50601801
 0.57503138 0.58516468 0.71079624 0.94368219]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [49]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

np.array_equal(A,B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [53]:
cartesian = np.random.rand(10,2)

x = cartesian[:,0]
y = cartesian[:,1]
r = np.sqrt(x**2+y**2)
theta = np.arctan2(y,x)
theta_degrees = np.degrees(theta)

polar = np.column_stack((r,theta_degrees))
print(polar)

[[0.21381705 0.3973305 ]
 [0.96324642 0.07202415]
 [0.20355694 0.85330802]
 [0.33485141 0.63214883]
 [0.41977815 0.43066524]
 [0.09886212 0.89525424]
 [0.60659508 0.51279428]
 [0.88681858 0.97521691]
 [0.88359181 0.23664408]
 [0.86148381 0.57964056]]
[[ 0.45120866 61.71379487]
 [ 0.96593537  4.27617961]
 [ 0.87725139 76.58282662]
 [ 0.71535838 62.08967741]
 [ 0.60140356 45.73344134]
 [ 0.90069633 83.69841123]
 [ 0.79430193 40.21001035]
 [ 1.31814081 47.71802079]
 [ 0.91473215 14.99312507]
 [ 1.03833402 33.93423442]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [59]:
A = np.random.random(10)
B = A.argmax()
A[B] = 0
print(A)

[0.81279484 0.22373501 0.10199058 0.34923552 0.59722121 0.86306142
 0.59858883 0.         0.42711111 0.09834083]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [62]:
Z = np.arange(100)
v = np.random.uniform(0,100)

index = (np.abs(Z-v)).argmin()
print(Z[index])

34


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [63]:
Z = np.arange(12).reshape(3,4)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [64]:
n = 4
p = 8
Z = np.zeros((4,4))
np.put(Z, np.random.choice(range(4*4), p, replace = False),8)
print(Z)

[[0. 0. 8. 8.]
 [8. 0. 0. 0.]
 [0. 0. 8. 8.]
 [0. 8. 8. 8.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [66]:
Z = np.random.randint(0,10,(3,3))
print(Z)

[[7 8 3]
 [0 7 8]
 [7 4 0]]


In [69]:
# column 1
sort_1 = Z[np.argsort(Z[:,0])]
print(sort_1)

[[0 7 8]
 [7 8 3]
 [7 4 0]]


In [68]:
# column 2
sort_2 = Z[np.argsort(Z[:,1])]
print(sort_2)

[[7 4 0]
 [0 7 8]
 [7 8 3]]


In [70]:
# column 3
sort_3 = Z[np.argsort(Z[:,2])]
print(sort_3)

[[7 4 0]
 [7 8 3]
 [0 7 8]]
